directories:
  output: dist_electron
  buildResources: build
  app: dist_electron/bundled
files:
  - filter:
      - '**'
extends: null
appId: dntrade-app
win:
  icon: src/assets/logo.png
electronVersion: 13.6.9
